# Generated by Django 5.0.6 on 2024-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='lunch_or_dinner',
            field=models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
