# Generated by Django 5.0.6 on 2024-07-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bookings', '0002_delete_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rate_us', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_header1', models.ImageField(blank=True, null=True, upload_to='about_header1/')),
                ('about_header2', models.ImageField(blank=True, null=True, upload_to='about_header2/')),
                ('about_header3', models.ImageField(blank=True, null=True, upload_to='about_header3/')),
                ('about_body1', models.ImageField(blank=True, null=True, upload_to='about_body1/')),
                ('register_image', models.ImageField(blank=True, null=True, upload_to='register_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('table_number', models.CharField(max_length=30)),
                ('lunch_or_dinner', models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
