# Generated by Django 5.0.6 on 2024-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_rename_tablestatus_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_header1', models.ImageField(upload_to='about_header1/')),
                ('about_header2', models.ImageField(upload_to='about_header2/')),
                ('about_header3', models.ImageField(upload_to='about_header3/')),
                ('about_body1', models.ImageField(upload_to='about_body1/')),
                ('register_image', models.ImageField(upload_to='register_image/')),
            ],
        ),
        migrations.DeleteModel(
            name='Table_Status',
        ),
    ]
