# Generated by Django 5.0.6 on 2024-06-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_rename_tablestatus_table_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table_Status',
        ),
    ]
