# Generated by Django 5.0.6 on 2024-06-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_alter_media_about_body1_alter_media_about_header1_and_more'),
        ('Bookings', '0006_images'),
    ]

    operations = [
    ]
