# Generated by Django 5.0.6 on 2024-06-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='about_bestrecipes',
            field=models.ImageField(blank=True, null=True, upload_to='about_bestrecipes/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='about_chef',
            field=models.ImageField(blank=True, null=True, upload_to='about_chef/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='about_moderninterior',
            field=models.ImageField(blank=True, null=True, upload_to='about_moderninterior/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='about_warmwelcome',
            field=models.ImageField(blank=True, null=True, upload_to='about_warmwelcome/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='book_register',
            field=models.ImageField(blank=True, null=True, upload_to='book_register/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='home_bg',
            field=models.ImageField(blank=True, null=True, upload_to='home_bg/'),
        ),
    ]
