# Generated by Django 5.0.6 on 2024-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_alter_feedbacks_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
