# Generated by Django 5.0.6 on 2024-06-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='lunch_or_dinner',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=10),
        ),
    ]
