# Generated by Django 5.0.6 on 2024-07-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0007_alter_feedbacks_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='feedback_image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_image/'),
        ),
    ]
