# Generated by Django 5.0.6 on 2024-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0010_alter_menuitem_description_alter_menuitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(default=True, null=True),
        ),
    ]
